model_list:
  - model_name: deepseek-r1:1.5b
    litellm_params:
      model: ollama/deepseek-r1:1.5b
      api_base: http://ollama:11434

router_settings:
  # Enable Redis Caching/Queuing
  redis_host: os.environ/REDIS_HOST
  # redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT

general_settings:
  # If SPO fills its 100 RPM, extra requests go to Redis Queue
  # Realtime requests bypass this queue because they have their own 700 RPM lane.
  allow_requests_queue: true